name: SQL Linting

on:
  push:
    paths:
      - 'DatabaseAdministration/Test/**/*.sql'  # Track SQL files in this folder
  pull_request:
    paths:
      - 'DatabaseAdministration/Test/**/*.sql'  # Also run on PRs

jobs:
  lint-sql-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify SQL Files Exist
        run: |
          echo "Checking for SQL files..."
          ls -R DatabaseAdministration/Test/ || echo "No SQL files found!"

      - name: Install SQLFluff
        run: |
          echo "Installing SQLFluff..."
          pip install sqlfluff

      - name: Run SQL Linting
        run: |
          echo "Running SQL linting..."
          sqlfluff lint "DatabaseAdministration/Test/*.sql" || echo "Linting failed!"
