name: Run SQL on SQL Server

on: [push, pull_request]

jobs:
  run-sql:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: test1234
        ports:
          - 1433:1433
        options: >-
          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SQL Server client
        run: sudo apt-get install -y mssql-tools unixodbc-dev

      - name: Run SQL files from DatabaseADmini/SQLSTATEMENT
        run: |
          for file in DatabaseAdministration/SQLStatements/*.sql; do
            echo "Executing $file..."
            /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -d master -i "$file"
          done
